### ISSUE TITLE
LineageOS Phone Encryption not working

### ISSUE THREAD

**Issue by ghost** [enesuzun2002/lineageos-ota#11]
When I enable Encryption on my Samsung s6 and Lineage OS 17.1 or any version, it just goes into a boot loop, you just see the Samsung logo  and then it reboots, it just repeats itself without the phone ever booting to Lineage OS ever again after that.

**Comment by Philzen** [comment]
Confirming this happens with both the recent 16.0 and 17.1 images found under releases. Trying to set up an S6 (G920F) for weeks now, and encryption is a must-have for me, so this slowly drains my enthusiasm about this (otherwise really nice) device.

I have tried numerous 17.1 images now, exactly the same thing happens for [Wickenberg](https://lineageos.wickenberg.nu/zeroflte/)s image and the one from the [LOS Legacy team](https://www.los-legacy.de/zerofltexx). So maybe this issue is possible to be solved in a concerted action with those teams, having everybody profit.

For what it's worth: Encryption works using [this three year old 15.0 image](https://mega.nz/folder/omZF1IQJ#2bk4dxzyW8ZwluqgrH945g/folder/k6ZzxBhZ) from Team Nexus found via [cyanogenmods.org](https://www.cyanogenmods.org/forums/topic/lineageos-15-galaxy-s6-android-oreo-8-0-rom/#LINEAGEOS15_INSTALLATION).
